version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: managers
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: ./app
    environment:
      DB_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      MANAGERS_DB: managers
      CLIENTS_DB: clients
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge