version: '3.8'

services: # Сервисы
  db: # База данных
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres  # Используем дефолтную базу для инициализации
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d managers" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: ./app
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: secret
      MANAGERS_DB: managers
      CLIENTS_DB: clients
    ports:
      - "8501:8501"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge